services:
  vllm-embed-rerank:
    image: bolz213/ubuntu-uv:ubuntu22.04-uv
    container_name: vllm-embed-rerank
    gpus: all
    ipc: host
    command: ["/scripts/start_embed_rerank.sh"]
    ports:
      - "8000:8000"
      - "8001:8001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
